# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMap',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('long', models.FloatField(verbose_name='Longitude')),
                ('zoom', models.PositiveSmallIntegerField(default=4, verbose_name='Zoom')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'GoogleMap',
                'verbose_name_plural': 'GoogleMaps',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('long', models.FloatField(verbose_name='Longitude')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlemaps.GoogleMap')),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
    ]
